version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    depends_on:
      - db
    environment:
      POSTGRES_DB: products
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/orders
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: sa1234

  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa1234
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: